apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-credentials
stringData:
  s3.config: |
    {
      "identities": [
       {
          "name": "root",
          "credentials":[
            {
              "accessKey": "aRandomString",
              "secretKey": "anotherRandomString"
            }
          ],
          "actions" : ["Read", "Write", "List", "Tagging", "Admin"]
       }
      ]
    }
