events{}

http{
	resolver kube-dns.kube-system.svc.cluster.local valid=10s;
	server{
		listen 80;

		location /api/v1{
			set $application_upstream http://application:8080/api/v1/;
            		proxy_pass $application_upstream;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		location /realms/ {
			set $keycloak_upstream http://keycloak:8080/realms/;
            		proxy_pass $keycloak_upstream;
	    		proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}

	server {
    		listen 8333;

		location / {
	        	set $seaweedfs_upstream http://seaweedfs:8333;
            		proxy_pass $seaweedfs_upstream;
			proxy_set_header Host $http_host;
	       		proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	 		proxy_set_header X-Forwarded-Proto $scheme;
    		}
	}
}
