spring:
  application:
    name: ResiAIAC

  data:
    web:
      pageable:
        max-page-size: 20

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8090/realms/ResiAIAC/protocol/openid-connect/certs

  datasource:
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PWD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
keycloak:
  admin:
    server-url: http://keycloak:8090
    realm: ResiAIAC
    client-id: resiaiac-admin-service
    secret: ${SPRING_KC_ADMIN_SECRET}
