apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: resiaiac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: keycloak-admin-credentials
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-postgres:5432/keycloak
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-credentials
                  key:  POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-credentials
                  key:  POSTGRES_PASSWORD
            - name: KC_HOSTNAME_STRICT
              value: "false"
